GET http://localhost:8080/api/users HTTP/1.1

###


POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
  "loginID": "asdf",
  "password": "asdf1234"
}

###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "loginID": "asdf",
  "password": "asdf1234"}

###

GET http://localhost:8080/api/users HTTP/1.1

### 특정 장소 조회
GET http://localhost:8080/api/places/ab1736c1-13c9-4df9-8440-4bf0ccb2a263 HTTP/1.1

### 장소 생성
POST http://localhost:8080/api/places HTTP/1.1
Content-Type: application/json

{
  "placeType": "SPOT",
  "placeName": "집",
  "latitude": 1,
  "longitude": 2,
  "etc": "서울울"
}

###
GET  http://localhost:8080/api/favorites/1efd1a4b-706a-6e71-a44d-e7b1f23b2697 HTTP/1.1

###
POST http://localhost:8080/api/recents HTTP/1.1
Content-Type: application/json

{
  "userID": "1efd1a4b-706a-6e71-a44d-e7b1f23b2697",
  "placeID": "ab1736c1-13c9-4df9-8440-4bf0ccb2a263"
}

###
POST http://localhost:8080/api/favorites HTTP/1.1
Content-Type: application/json

{
  "userID": "1efd1a4b-706a-6e71-a44d-e7b1f23b2697",
  "placeID": "ab1736c1-13c9-4df9-8440-4bf0ccb2a263",
  "favoriteName": "기숙사"
}

###
POST http://localhost:8080/api/paths HTTP/1.1
{
  "userID": "string",
  "originID": "string",
  "destinationID": "string",
  "totalDistance": 0,
  "totalTime": "string"
}

###
GET http://localhost:8080/api/paths/1efd241d-46e3-6f36-9c66-0f2a18e8923f/recents HTTP/1.1